server:
  profile:
    - duration: 60s
      latency_distribution:
      - weight: 90
        latency: 10ms
      - weight: 5
        latency: 50ms
      - weight: 4
        latency: 100ms
      - weight: 1
        latency: 250ms
    - duration: 60s
      latency_distribution:
      - weight: 90
        latency: 25ms
      - weight: 5
        latency: 50ms
      - weight: 4
        latency: 100ms
      - weight: 1
        latency: 250ms
    - duration: 60s
      latency_distribution:
      - weight: 95
        latency: 75ms
      - weight: 4
        latency: 100ms
      - weight: 1
        latency: 250ms
  listen_port: 9002
  threads: 4
