client:
  workload:
    - rps: 200
      duration: 20s
    - rps: 350
      duration: 20s
    - rps: 200
      duration: 20s
    - rps: 350
      duration: 20s
    - rps: 200
      duration: 20s
    - rps: 350
      duration: 20s
    - rps: 200
      duration: 20s
    - rps: 350
      duration: 20s
    - rps: 200
      duration: 20s
  rq_timeout: 5s
  target_server:
    address: 0.0.0.0
    port: 9001
server:
  profile:
    - duration: 60s
      latency_distribution:
      - weight: 90
        latency: 10ms
      - weight: 5
        latency: 50ms
      - weight: 4
        latency: 100ms
      - weight: 1
        latency: 250ms
    - duration: 60s
      latency_distribution:
      - weight: 90
        latency: 25ms
      - weight: 5
        latency: 50ms
      - weight: 4
        latency: 100ms
      - weight: 1
        latency: 250ms
    - duration: 60s
      latency_distribution:
      - weight: 95
        latency: 75ms
      - weight: 4
        latency: 100ms
      - weight: 1
        latency: 250ms
  listen_port: 9002
  threads: 4
