client:
  workload:
    - rps: 200
      duration: 20s
    - rps: 350
      duration: 20s
    - rps: 200
      duration: 20s
    - rps: 350
      duration: 20s
    - rps: 200
      duration: 20s
    - rps: 350
      duration: 20s
    - rps: 200
      duration: 20s
    - rps: 350
      duration: 20s
    - rps: 200
      duration: 20s
  rq_timeout: 5s
  target_server:
    address: 0.0.0.0
    port: 19002