client:
  - workload:
      - rps: 50
        duration: 5s
      - rps: 400
        duration: 5s
    rq_timeout: 1s
    target_server:
      address: 0.0.0.0
      port: 9002
  - workload:
      - rps: 50
        duration: 10s
    rq_timeout: 1s
    target_server:
      address: 0.0.0.0
      port: 9002
server:
  profile:
    - duration: 10s
      latency_distribution:
      - weight: 90
        latency: 50ms
      - weight: 5
        latency: 60ms
      - weight: 4
        latency: 100ms
      - weight: 1
        latency: 150ms
  listen_port: 9002
  threads: 8
  max_queue_size: 1000
  max_active_rq: 50
  queue_timeout: 10ms # 0 means no timeout
