client:
  workload:
    - rps: 2000
      duration: 30s
  rq_timeout: 1s
  target_server:
    address: 0.0.0.0
    port: 9001
server:
  profile:
    - duration: 31s
      latency_distribution:
      - weight: 1
        latency: 10ms
  listen_port: 9002
  threads: 8
  server_count: 5
