client:
  workload:
    - rps: 10
      duration: 10s
    - rps: 100
      duration: 1s
    - rps: 10
      duration: 29s
  rq_timeout: 5s
  target_server:
    address: 0.0.0.0
    port: 9002
server:
  profile:
    - rq_latency: 200ms
      duration: 30s
  listen_port: 9002
  threads: 4
