client:
  workload:
    - rps: 100
      duration: 20s
    - rps: 110
      duration: 5s
    - rps: 120
      duration: 5s
    - rps: 130
      duration: 5s
    - rps: 140
      duration: 20s
  rq_timeout: 1s
  target_server:
    address: 0.0.0.0
    # port: 9001
    port: 19002
