client:
  workload:
    - rps: 100
      duration: 20s
    - rps: 110
      duration: 5s
    - rps: 120
      duration: 5s
    - rps: 130
      duration: 5s
    - rps: 140
      duration: 20s
  rq_timeout: 1s
  target_server:
    address: 0.0.0.0
    # port: 9001
    port: 9002
server:
  profile:
    - duration: 5500s
      latency_distribution:
      - weight: 90
        latency: 50ms
      - weight: 5
        latency: 60ms
      - weight: 4
        latency: 100ms
      - weight: 1
        latency: 150ms
  listen_port: 9002
  threads: 8
