client:
  - workload:
      - rps: 20
        duration: 2s
      - rps: 25
        duration: 2s
      - rps: 30
        duration: 2s
      - rps: 35
        duration: 2s
      - rps: 40
        duration: 2s
      - rps: 45
        duration: 2s
      - rps: 50
        duration: 2s
      - rps: 55
        duration: 2s
      - rps: 60
        duration: 2s
      - rps: 65
        duration: 2s
      - rps: 70
        duration: 10s
    rq_timeout: 2s
    target_server:
      address: 0.0.0.0
      port: 9002
  - workload:
      - rps: 20
        duration: 30s
    rq_timeout: 2s
    target_server:
      address: 0.0.0.0
      port: 9002
  - workload:
      - rps: 20
        duration: 30s
    rq_timeout: 2s
    target_server:
      address: 0.0.0.0
      port: 9002
        # - workload:
        #     - rps: 20
        #       duration: 30s
        #   rq_timeout: 2s
        #   target_server:
        #     address: 0.0.0.0
        #     port: 9002
        # - workload:
        #     - rps: 20
        #       duration: 30s
        #   rq_timeout: 2s
        #   target_server:
        #     address: 0.0.0.0
        #     port: 9002
server:
  profile:
    - duration: 30s
      latency_distribution:
      - weight: 90
        latency: 50ms
      - weight: 5
        latency: 100ms
      - weight: 4
        latency: 150ms
      - weight: 1
        latency: 200ms
  listen_port: 9002
  threads: 4
  max_queue_size: 100
  queue_timeout: 200ms # 0 means no timeout
  enable_isolation: false
