server:
  profile:
    - duration: 600s
      latency_distribution:
      - weight: 90
        latency: 50ms
      - weight: 5
        latency: 60ms
      - weight: 4
        latency: 100ms
      - weight: 1
        latency: 150ms
  listen_port: 9002
  threads: 4
